version: '2.1'

services:
  chairlift:
    image: chairlift
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 bin/server