version: '3.7'

services:
  app:
    container_name: chairlift
    networks:
      - chairlift
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - './config/.env'
    volumes:
      - './config:/app/config'
      - './src:/app/src'
      - './doc:/app/doc'
    ports:
      - 80:80
      - 4003:4003
      # - 9229:9229
    depends_on:
      - postgres
    entrypoint:
      - ./entrypoint.sh
      - ./node_modules/.bin/nodemon
      #- --inspect-brk=0.0.0.0 , break before code starts
      #- --inspect=0.0.0.0
      - ./bin/server

  postgres:
    image: postgres:12.1    
    container_name: charilift-db
    networks:
      - chairlift
    environment:
      POSTGRES_DB: "${TYPEORM_DATABASE}"
      POSTGRES_USER: "${TYPEORM_USERNAME}"
      POSTGRES_PASSWORD: "${TYPEORM_PASSWORD}"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  postgres: ~

networks:
  chairlift:
    name: chairlift
